
source 'https://github.com/yangqingren/Spec.git'

use_frameworks!

platform :ios, '8.0'

target 'LBCocoaSpecKit_Example' do
  pod 'LBCocoaSpecKit', :path => '../'

  target 'LBCocoaSpecKit_Tests' do
    inherit! :search_paths

    
  end
end
